# Generated by Django 5.2.3 on 2025-06-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chamado', models.IntegerField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('tecnicos', models.CharField(max_length=200)),
                ('data_abertura', models.DateTimeField(auto_now=True)),
                ('data_atendimento', models.DateTimeField(auto_now=True)),
                ('horario_atendimento', models.TimeField()),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('nivel', models.CharField(blank=True, max_length=200, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['data_atendimento'],
            },
        ),
    ]
