# Generated by Django 5.2.3 on 2025-06-25 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bairro_chamado', to='clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidade_chamado', to='clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente_chamado', to='clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endereco_chamado', to='clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_chamado', to='clientes.clientes'),
        ),
    ]
