# Generated by Django 5.2.3 on 2025-06-26 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_alter_chamados_bairro_alter_chamados_cidade_and_more'),
        ('clientes', '0003_statusclientes_alter_clientes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bairro_chamado', to='clientes.bairro'),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidade_chamado', to='clientes.cidade'),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='data_atendimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_chamado', to='clientes.estado'),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel_chamado', to='clientes.nivel'),
        ),
    ]
