# Generated by Django 5.2.3 on 2025-06-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_alter_chamados_bairro_alter_chamados_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
