# Generated by Django 5.2.3 on 2025-06-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_alter_chamados_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='cliente',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='chamados',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
    ]
