# Generated by Django 5.2.3 on 2025-06-28 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_alter_chamados_cliente_alter_chamados_endereco'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamados',
            name='tecnicos',
        ),
        migrations.AddField(
            model_name='chamados',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tecnicos_chamado', to='tecnicos.tecnicos'),
        ),
    ]
