# Generated by Django 5.2.3 on 2025-06-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_remove_chamados_tecnicos_chamados_tecnico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamados',
            old_name='tecnico',
            new_name='tecnicos',
        ),
    ]
