# Generated by Django 5.2.3 on 2025-06-28 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_rename_tecnico_chamados_tecnicos'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='tecnicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicos_chamado', to='tecnicos.tecnicos'),
        ),
    ]
