# Generated by Django 5.2.3 on 2025-06-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_alter_chamados_tecnicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamados',
            name='id',
        ),
        migrations.AlterField(
            model_name='chamados',
            name='numero_chamado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
