# Generated by Django 5.2.3 on 2025-06-26 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_alter_nivel_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacaoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('rg', models.CharField(blank=True, default=0, null=True)),
                ('cpf', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=200)),
                ('n3', models.IntegerField(blank=True, default=0, null=True)),
                ('n2', models.IntegerField(blank=True, default=0, null=True)),
                ('n1', models.IntegerField(blank=True, default=0, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bairro_tecnicos', to='clientes.bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidade_tecnicos', to='clientes.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado_tecnicos', to='clientes.estado')),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formacao_tecnicos', to='tecnicos.formacaotecnico')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel_tecnicos', to='clientes.nivel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_tecnicos', to='clientes.statusclientes')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
