# Generated by Django 5.2.3 on 2025-06-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(max_length=10)),
            ],
            options={
                'ordering': ['nivel'],
            },
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nivel_cliente', to='clientes.nivel'),
        ),
    ]
