# Generated by Django 5.2.3 on 2025-06-26 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_nivel_alter_clientes_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.AlterField(
            model_name='clientes',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuscliente_cliente', to='clientes.statusclientes'),
        ),
    ]
